account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

# internalImport 
from . import views
from .forms import UserLoginForm,  PwdResetForm ,PwdResetConfirmForm

app_name = 'account'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('success/', views.success, name='success'),
    path('settings/', views.edit_detail, name='settings'),


    # Auth
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),

    # resetPAssword
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),

    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_confirm/Mw/password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # User dashboard

]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('order.urls', namespace='order')),
    path('feed/', include('feed.urls', namespace='feed')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

feed/urls.py
from django.urls import path
from .views import Feed

app_name  = 'feed'

urlpatterns = [
    path('social/', Feed.as_view(), name='feed')
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('<str:ref_code>/', views.home, name='main-view'),
    path('giveaway/<slug:category_slug>/', views.category_list, name='category_list'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('view/all/', views.Product_all.as_view(), name='product_all'),

]

templates/account_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link rel="shortcut icon" href= {% static 'images/favicon.png' %} />
    <title>{% block title %} {% endblock %}</title>

    <!--Font awsom link-->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />


    <!-- Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
</head>
<style>
@import url("https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;600;700&display=swap");
body{
    font-family: "Nunito", sans-serif;
}
</style>
<body>

<div class="px-4 py-5 my-50 text-center">
    <a href="/">
        <img class="d-block mx-auto mb-4" src="{% static 'images/product-1.jpg' %}" alt="" width="72" height="57">
    </a>
</div>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Favicon -->
    <link rel="shortcut icon" href= {% static 'images/favicon.png' %} />
    
    <!-- Font Awesome -->

    <!-- ======== Swiper Js ======= -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.7.5/swiper-bundle.min.css"
    />
  
    <!-- ========= HEADER SLIDER ==========-->
    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />
    <!--==========STORE CSS ================-->
    <link rel="stylesheet" href="{% static 'css/store/header-slider.css' %}" />

    <!-- font awesome cdn link  -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />

    <!-- Bootstrap -->

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    {% block header %}
    {% endblock header %}

    <!-- Boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.0.8/css/boxicons.min.css"
      rel="stylesheet"/>

    <link rel="stylesheet" href="{% static 'css/store/main.css' %}" />
    <title>{% block title %}GoogleGiveaway{% endblock title %}</title>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="nav">
      <div class="wrapper container">
        <div class="logo">
          <a href="/">
            <img src="#" alt="GoogleGiveaway" />
          </a>
        </div>
        <ul class="nav-list">
          <div class="top">
            <label for="" class="btn close-btn"
              ><i class="fas fa-times"></i
            ></label>
          </div>

          <li>
            <a href="" class="desktop-item"
              >Giveaway<span><i class="fas fa-chevron-down"></i></span
            ></a>
            <input type="checkbox" id="showMega" />
            <label for="showMega" class="mobile-item"
              >Giveaway<span><i class="fas fa-chevron-down"></i></span
            ></label>
            <div class="mega-box">
              <div class="content">
                <div class="row">
                  <img src="{% static 'images/nav.png' %}" alt="nav.png" />
                </div>
                <div class="row">
                  <header>Giveaway's</header>
                  <ul class="mega-links">
                    <li><a href="{% url 'store:product_all' %}">All</a></li>
                    {% for item in categories %}
                    <li><a href="{{item.get_absolute_url}}">{{item.name}}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </li>

          <li>
            <a href="" class="desktop-item"
              >Billboard<span><i class="fas fa-chevron-down"></i></span
            ></a>
            <input type="checkbox" id="showdrop1" />
            <label for="showdrop1" class="mobile-item"
              >Billboard<span><i class="fas fa-chevron-down"></i></span
            ></label>
            <ul class="drop-menu1">
              <li><a href="{% url 'feed:feed' %}">Billboard</a></li>
            </ul>
          </li>

          <li>
            <a href="" class="desktop-item"
              >Account <span><i class="fas fa-chevron-down"></i></span
            ></a>
            <input type="checkbox" id="showdrop2" />
            <label for="showdrop2" class="mobile-item"
              >Account <span><i class="fas fa-chevron-down"></i></span
            ></label>
            <ul class="drop-menu2">
            {% if user.is_authenticated %}
              <li><a href="{% url 'account:logout'%}">Log Out</a></li>
              <li><a href="{% url 'account:dashboard'%}">Dashboard</a></li>
              <li><a href="{% url 'account:dashboard'%}">My Entries </a></li>
              <li><a href="{% url 'account:dashboard'%}">Settings</a></li>
            {%else%}
              <li><a href="{% url 'account:register'%}">Register</a></li>
              <li><a href="{% url 'account:login'%}">Log In</a></li>
            {% endif %}
            
            </ul>
          </li>

          <!-- icons -->
          <li class="icons">
            {% comment %} add cart lik here {% endcomment %}
            {% comment %} <a href="#">
              <span>
                <img src= {% static 'images/shoppingBag.svg' %} alt="" />
                <small id="cart" class="count d-flex">0</small>
              </span>
            </a> {% endcomment %}
          </li>
        </ul>
        <label for="" class="btn open-btn"><i class="fas fa-bars"></i></label>
      </div>
    </nav>
<!--############################################################## CONTENT ###################################################################-->
    {% block content %}
    {% endblock content %}
<!--############################################################## END CONTENT ###################################################################-->
    
    <!-- Footer -->
    <footer id="footer" class="section footer">
    <div class="container">
      <div class="footer-container">
        <div class="footer-center">
          <h3>EXTRAS</h3>
          <a href="#">Brands</a>
          <a href="#">Gift Certificates</a>
          <a href="#">Affiliate</a>
          <a href="#">Specials</a>
          <a href="#">Site Map</a>
        </div>
        <div class="footer-center">
          <h3>INFORMATION</h3>
          <a href="#">About Us</a>
          <a href="#">Privacy Policy</a>
          <a href="#">Terms & Conditions</a>
          <a href="#">Contact Us</a>
          <a href="#">Site Map</a>
        </div>
        <div class="footer-center">
          <h3>MY ACCOUNT</h3>
          <a href="#">My Account</a>
          <a href="#">Order History</a>
          <a href="#">Wish List</a>
          <a href="#">Newsletter</a>
          <a href="#">Returns</a>
        </div>
        <div class="footer-center">
          <h3>CONTACT US</h3>
          <div>
            <span>
              <i class="fas fa-map-marker-alt"></i>
            </span>
            42 Dream House, Dreammy street, 7131 Dreamville, USA
          </div>
          <div>
            <span>
              <i class="far fa-envelope"></i>
            </span>
            company@gmail.com
          </div>
          <div>
            <span>
              <i class="fas fa-phone"></i>
            </span>
            456-456-4512
          </div>
          <div class="payment-methods">
            <img src="{% static 'images/payment.png' %}" alt="">
          </div>
        </div>
      </div>
    </div>
    </div>
    </footer>
  <!-- End Footer -->

    <!-- ======== SwiperJS ======= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.7.5/swiper-bundle.min.js"></script>

    <!-- Main Scripts -->
    <script src="{% static 'js/store/slider.js' %}"></script>
    <script src="{% static 'js/store/main.js' %}"></script>

    <!-- main header slider -->
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="{% static 'js/store/header-slider.js' %}"></script>

    {% block js %}
    {% endblock js %}

  </body>
</html>