core/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('order.urls', namespace='order')),
    path('feed/', include('feed.urls', namespace='feed')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path
from . import views 

app_name  = 'order'

urlpatterns = [
    path('<str:slug>/', views.checkout, name='checkout'),
    path('payment/verifyPayment/', views.verifyPayment, name='verify_payment'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('<str:ref_code>/', views.home, name='main-view'),
    path('giveaway/<slug:category_slug>/', views.category_list, name='category_list'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('view/all/', views.Product_all.as_view(), name='product_all'),

]

store/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


# model only passes the active product
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    image = models.ImageField()
    slug = models.SlugField(max_length=100, unique=True)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    is_active = models.BooleanField(default=True)
    is_lastchance = models.BooleanField(default=False)
    is_trending = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    objects = models.Manager()
    products = ProductManager

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)
    
    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])
    
    def __str__(self):
        return self.title

store/views.py
from refferal.models import Refferal
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView


# Model Import
from .models import Category, Product
from order.models import Order, Payment
from feed.models import UplodedPic

# Create your views here.


def home(request, *args, **kwargs):
    code = str(kwargs.get('ref_code'))
    try:
        # get the code of the person who reffered
        refferal = Refferal.objects.get(code=code)
        request.session['ref_profile'] = refferal.id
        print('id', refferal.id)
    except:
        pass
    print(request.session.get_expiry_age())

    is_lastchance =  Product.objects.filter(is_lastchance=True)
    is_trending = Product.objects.filter(is_trending=True)
    
    context = {
        'is_lastchance': is_lastchance,
        'is_trending': is_trending
    }

    return render(request, 'store/home.html', context)


def category_list(request, category_slug=None):
    # Category.objects.filter(slug=category_slug)
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    context =  {
        'category': category,
        'products': products
    }
    return render(request, 'store/category.html', context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)

    # user profile recommendation 
    pr = product.id 
    ord = Order.objects.filter(product__id=pr)
    user_dict = {}
    for item in ord:
        up = UplodedPic.objects.filter(user=item.user.id)
        
        for item in up:   
            user_dict.update({f"{item.user.user_name}": f"{item.img.url}"})
    print(user_dict)
 
   
    context = {
        'product': product,
        'user_dict': user_dict       
    }
   
    return render(request, 'store/product_detail.html', context)


class Product_all(ListView):
    context_object_name = 'product'
    model = Product
    template_name = 'store/products_all.html'

templates/store/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="container">
    <div class="row">
      <div class="album py-5">


        <div class="pb-3"><h1 class="h3">{{category.name}}</h1></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

          {% for product in products %}

          <div class="col">
            <div class="card border-0">
              <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none"
                    href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">£{{product.price}}</small>
                </div>
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
      </div>
    </div>

  </div>


</main>

{% endblock %}

templates/store/home.html
{% extends '../base.html' %}
{% load static %}


{% block content %}


<section class="home" id="home">

    <div class="content">
        <h3>app landing page</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima labore similique eos harum atque omnis ex consectetur, assumenda sunt ad facilis illum quaerat doloremque. Aut eveniet culpa enim suscipit ullam!</p>
        <a href="#" class="btn-01">get started</a>
    </div>

    <div class="swiper-container image-slider">
        <div class="swiper-wrapper">
            <div class="swiper-slide"><img src="images/shot-01.jpg" alt=""></div>
            <div class="swiper-slide"><img src="images/shot-02.jpg" alt=""></div>
            <div class="swiper-slide"><img src="images/shot-03.jpg" alt=""></div>
            <div class="swiper-slide"><img src="images/shot-04.jpg" alt=""></div>
            <div class="swiper-slide"><img src="images/shot-05.jpg" alt=""></div>
        </div>
    </div>

</section>



<!-- ########################################################## How it work ######################################### -->
<section class="features" id="features">

  <h1 class="heading" id="h-text">app features</h1>

  <div class="box-container">

      <div class="box">
          <i class="fas fa-magic"></i>
          <h3>smooth design</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque enim ad neque. Voluptatem alias beatae accusamus laudantium nisi assumenda libero.</p>
      </div>
      <div class="box">
          <i class="fas fa-shield-alt"></i>
          <h3>privacy protect</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque enim ad neque. Voluptatem alias beatae accusamus laudantium nisi assumenda libero.</p>
      </div>
      <div class="box">
          <i class="fas fa-globe"></i>
          <h3>multiple language</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque enim ad neque. Voluptatem alias beatae accusamus laudantium nisi assumenda libero.</p>
      </div>
      <div class="box">
          <i class="fas fa-map-marker-alt"></i>
          <h3>location tracking</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque enim ad neque. Voluptatem alias beatae accusamus laudantium nisi assumenda libero.</p>
      </div>
      <div class="box">
          <i class="fas fa-cogs"></i>
          <h3>powerfull settings</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque enim ad neque. Voluptatem alias beatae accusamus laudantium nisi assumenda libero.</p>
      </div>
      <div class="box">
          <i class="fas fa-headset"></i>
          <h3>24 x 7 service</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque enim ad neque. Voluptatem alias beatae accusamus laudantium nisi assumenda libero.</p>
      </div>

  </div>

</section>
<!-- ############################################# HOW ITS WORK END ##################################################### -->
  <!-- Promotion -->
  <section class="section promotion">
    <div class="title">
      <h1 id="h-text" class="heading">CATEGORIES</h1>
      <span>Select from the premium product and save plenty money</span>
    </div>

    <div class="promotion-layout container">
      <div class="promotion-item">
        <img src="{% static 'images/gadgets.jpg' %}" alt="" />
        <div class="promotion-content">
        </div>
      </div>

      <div class="promotion-item">
        <img  src="{% static 'images/skin.png' %}" alt="" />
        <div class="promotion-content">
        </div>
      </div>

      <div class="promotion-item">
        <img src="{% static 'images/vacation.jpg' %}" alt="" />
        <div class="promotion-content">
        </div>
      </div>

    </div>
  </section>

  <!-- =================================== LAST CHANCE ======================================================= -->
  <section class="section featured">
    <div class="title">
      <h1 id="h-text" class="heading">LAST CHANCE</h1>
      <!-- <span>Select from the premium product brands and save plenty money</span> -->
    </div>

    <div class="row container">
      <div class="swiper-container slider-2">
        <div class="swiper-wrapper">
          {% for item in is_lastchance %}
            <div class="swiper-slide">
                <div class="product" >
                  <div class="img-container" >
                    <img src="{{item.image.url }}" alt="" />
                  </div>
                  <div class="bottom">
                    <div class="price">
                      <span>{{item.title}}</span>
                    </div>
                    <a href="{{item.get_absolute_url}}">{{item.description}}</a>
                  </div>
                </div>
            </div>
          {% endfor %}
        </div>
      </div>
      {% comment %} <a class="btn btn-outline-dark" id="mob-btn" href="#" role="button">View</a> {% endcomment %}

    </div>

     <!-- Carousel Navigation -->
    <div class="arrows d-flex">
       <div class="custom-next d-flex">
          <i class="bx bx-chevrons-right swiper-icon"></i>
        </div>
        <div class="custom-prev d-flex">
          <i class="bx bx-chevrons-left swiper-icon"></i>
        </div>
    </div>
  </section>

  <!-- ###################################### ===> Trending <=== ############################################ -->

  <section class="section featured">
    <div class="title">
      <h1 id="h-text" class="heading" >Trending</h1>
      <!-- <span>Select from the premium product brands and save plenty money</span> -->
    </div>

    <div class="row container">
      <div class="swiper-container slider-2">
        <div class="swiper-wrapper">
          {% for item in is_trending %}
            <div class="swiper-slide">
              <div class="product" >
                <div class="img-container" >
                  <img src="{{item.image.url}}" alt="" />
                </div>
                <div class="bottom">
                  <div class="price">
                    <span>{{item.title}}</span>
                  </div>
                  <a href="{{item.get_absolute_url}}"> {{item.description}}</a>
                </div>
              </div>
            </div>
          {% endfor %}

        </div>
      </div>

    </div>

     <!-- Carousel Navigation -->
    <div class="arrows d-flex">
       <div class="custom-next d-flex">
          <i class="bx bx-chevrons-right swiper-icon"></i>
        </div>
        <div class="custom-prev d-flex">
          <i class="bx bx-chevrons-left swiper-icon"></i>
        </div>
    </div>
    {% comment %} <a class="btn btn-outline-dark" id="mob-btn" href="#" role="button">View</a> {% endcomment %}

  </section>

  <!-- #########################################################People who participated #######################################  -->
  <section class="section products">
    <div class="title">
      <h1  id="h-text" class="heading" >BILLBOARD</h1>
      <span><i> People who participated.
      </i> </span>
    </div>

    <div class="product-layout">

      <div class="product">
        <div class="img-container">
          <img src="{% static 'images/product-1.jpg' %}" alt="" />
          <div class="addCart">
            <i class="far fa-heart"></i>
          </div>
        </div>
        <div class="bottom">
          <a href="">User Name</a>
          <div class="price">
            <span style="font-size: smaller;">products</span>
          </div>
        </div>
      </div>

      <div class="product">
        <div class="img-container">
          <img src="{% static './images/product-1.jpg' %}" alt="" />
          <div class="addCart">
            <i class="far fa-heart"></i>
          </div>
        </div>
        <div class="bottom">
          <a href="">User Name</a>
          <div class="price">
            <span style="font-size: smaller;">products</span>
          </div>
        </div>
      </div>

      <div class="product">
        <div class="img-container">
          <img src="{% static './images/product-1.jpg' %}" alt="" />
          <div class="addCart">
            <i class="far fa-heart"></i>
          </div>
        </div>
        <div class="bottom">
          <a href="">User Name</a>
          <div class="price">
            <span style="font-size: smaller;">products</span>
          </div>
        </div>
      </div>

      <div class="product">
        <div class="img-container">
          <img src="{% static './images/product-1.jpg' %}" alt="" />
          <div class="addCart">
            <i class="far fa-heart"></i>
          </div>
        </div>
        <div class="bottom">
          <a href="">User Name</a>
          <div class="price">
            <span style="font-size: smaller;">products</span>
          </div>
        </div>
      </div>

    </div>
    <a class="btn btn-outline-dark" id="mob-btn" href="#" role="button">View</a>

  </section>

<!-- ############################################################# FAQ ########################################## -->
<section class="section products" >
  <div class= "title">
    <h1 id="h-text" class="heading" >FAQ</h1>
    <span><i> Frequently asked question.</i> </span>
  </div>
  
  <div class="product">
    <div class="accordion container-lg " id="accordionExample">
      <!-- #1 -->
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" style="height: 50px; font-size: large;" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Accordion Item #1
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
          </div>
        </div>
      </div>
      <!-- #2 -->
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
          <button class="accordion-button collapsed " style="height: 50px; font-size: large;" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Accordion Item #2
          </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
          </div>
        </div>
      </div>
      <!-- #3 -->
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingThree">
          <button class="accordion-button collapsed" style="height: 50px; font-size: large;" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            Accordion Item #3
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- #################################################################### FAQ END ################################################# -->
{% endblock%}

templates/store/product_detail.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
  <!-- Product Details -->
  <section class="section product-detail">
    <div class="details container">
      <div class="left">
        <div class="main" style="margin-top:-90px">
          <img src="{{product.image.url}}" alt="" />
        </div>
        
      </div>
      <div class="right" id="mob-right">
        <h1>{{product.title}}</h1>
        <div class="price">₹ {{product.price}}</div>
        <form class="form">
          <a href="{% url 'order:checkout' product.slug %}" class="addCart" style="background-color: #0B5ED7"> Enter Now</a>
        </form>
        <h3>PRODUCT DETAIL</h3>
        <p>
          {{product.description}}
        </p>
      </div>
    </div>
  </section>

    {% comment %} <div class="b-example-divider"></div> {% endcomment %}

      <!-- ###################################### ===> Recommended Profile <=== ############################################ -->

  <section class="section featured">
    <div class="title">
      <h2 id="h-text" class="heading" >People who joined this giveaway</h2>
      <!-- <span>Select from the premium product brands and save plenty money</span> -->
    </div>

    <div class="row container">
      <div class="swiper-container slider-2">
        <div class="swiper-wrapper">
          {% for key, value in user_dict.items %}
            <div class="swiper-slide">
              <div class="product" >
                <div class="img-container" >
                  <img src="{{value}}" alt="" />
                </div>
                <div class="bottom">
                  <div class="price">
                  
                    <span>{{key}}</span>
              
                  </div>
                  <a href="#"></a>
                </div>
              </div>
            </div>
          {% endfor %}

        </div>
      </div>

    </div>

     <!-- Carousel Navigation -->
    <div class="arrows d-flex">
       <div class="custom-next d-flex">
          <i class="bx bx-chevrons-right swiper-icon"></i>
        </div>
        <div class="custom-prev d-flex">
          <i class="bx bx-chevrons-left swiper-icon"></i>
        </div>
    </div>
    {% comment %} <a class="btn btn-outline-dark" id="mob-btn" href="#" role="button">View</a> {% endcomment %}

  </section>

  


{% endblock %}

templates/store/products_all.html
{% extends '../base.html' %}
{% load static %}


{% block content %}
\  <!-- #########################################################People who participated #######################################  -->
  <section class="section products">
    <div class="title">
      <h1  id="h-text" class="heading" >Giveaway's</h1>
      </i> </span>
    </div>

    <div class="product-layout">
      
      {% for product in product %}
        <div class="product">
          <div class="img-container">
            <img onclick="window.open('{{product.get_absolute_url}}')" src="{{ product.image.url }}" alt="" />
          </div>
          <div class="bottom">
            <a href="{{product.get_absolute_url}}">{{ product.title|slice:":50" }}</a>
            <div class="price">
              <span style="font-size: smaller;">{{product.description}}</span>
            </div>
          </div>
        </div>
      {% endfor %}

      {% for product in product %}
        <div class="product">
          <div class="img-container">
            <img src="{{ product.image.url }}" alt="" />
          </div>
          <div class="bottom">
            <a href="{{product.get_absolute_url}}">{{ product.title|slice:":50" }}</a>
            <div class="price">
              <span style="font-size: smaller;">{{product.description}}</span>
            </div>
          </div>
        </div>
      {% endfor %}
     </div>
    </div>

  </section>

{% endblock %}