core/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('order.urls', namespace='order')),
    path('feed/', include('feed.urls', namespace='feed')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path
from . import views 

app_name  = 'order'

urlpatterns = [
    path('<str:slug>/', views.checkout, name='checkout'),
    path('payment/verifyPayment/', views.verifyPayment, name='verify_payment'),
]

order/models.py
from django.db import models
from store.models import Product
from django.conf import settings




# it store all user order that had been successfuly purchased
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, null=False, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user.user_name}--{self.product.title}"


class Payment(models.Model):
    order_id = models.CharField(max_length=50, null=False)
    payment_id = models.CharField(max_length=50)
    
    # user_product only store the item which had been purchased by user
    user_product = models.ForeignKey(Order, null=True, blank=True, on_delete=models.CASCADE)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # all the product store that thagt had been purchased or the transection of item had been failed
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

order/views.py
from django.shortcuts import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from time import time
import razorpay

# internal import
from store.models import Product 
from .models import Order, Payment


"""Razorpay client """
client = razorpay.Client(auth=(settings.KEY_ID, settings.KEY_SECRET))

@login_required
def checkout(request, slug):
    product = Product.objects.get(slug=slug)

    user = request.user

    action = request.GET.get('action')
    order = None
    payment = None
    error = None
    if action == "create_payment":

        try:
            user_product = Order.objects.get(user=user, product=product)
            error = "You are already enroled in this cource"
        except:
            pass
        
        # checking the error 
        if error is None:

            amount = int((product.price)*100)
            currency = "INR"
            notes = {
                "email": user.email,
                "name": user.user_name

            }
            
            receipt = f"GoogleGiveaway-{int(time())}"
            order = client.order.create({
                'receipt':receipt,
                'notes':notes,
                'amount':amount,
                'currency':currency
            })
            

            payment = Payment.objects.create(
                user=user,
                product=product,
                order_id=order.get('id'),    
            )
            payment.save()

    context = {
        'product': product,
        'order': order,
        'payment': payment,
        'error':error 
    }
    return render(request, 'order/checkout.html', context)


@csrf_exempt
def verifyPayment(request):
    if request.method == 'POST':
        data = request.POST
        try:
            client.utility.verify_payment_signature(data)
            # data.get method does not throw exception but data['data'] thow's the exception
            razorpay_order_id = data['razorpay_order_id']
            razorpay_payment_id = data['razorpay_payment_id']

            print(razorpay_payment_id, razorpay_order_id)
            
            # .get gives us one query data and . fliter gives us more then 1 query data
            payment = Payment.objects.get(order_id=razorpay_order_id)
            payment.payment_id = razorpay_payment_id
            payment.status = True

            order = Order.objects.create(user=payment.user, product=payment.product)
            order.save()
            print("UserProduct", order.id)

            payment.user_product = order
            payment.save()
            return render(request, template_name='order/my_order.html')

        except Exception as ex:
            return HttpResponse("Invalid payment Detail")
    
    
    

templates/order/checkout.html
<!DOCTYPE html>
{% load static %}
{% comment %} f3f3f3 {% endcomment %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Checkout</title>
  <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
  />
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
  ></script>
  <link rel="stylesheet" href="{% static 'css/order/checkout.css' %}">
   
</head>
<body>

  <div class="b-example-divider"></div>

<div class='container'>
  <div class='window'>
    <div class='order-info'>
      <div class='order-info-content'>
        <h2>Order Summary</h2>
                <div class='line'></div>
        <table class='order-table'>
          <tbody>
            <tr>
              <td><img src="{{product.image.url}}" class='full-width'></img>
              </td>
              <td>
                <br> <span class='thin'>{{product.title}}</span>
                <br > win <br> <span class='thin small'>{{product.title}}....<br><br></span>
              </td>

            </tr>
            <tr>
              <td>
                <div class='price'>₹ {{product.price}}</div>
              </td>
            </tr>
          </tbody>

        </table>
        <div class='line'></div>
        
        <div class='total'>
          <span style='float:left;'>
            <div class='thin dense'>GST 18%</div>
            <div class='thin dense'>Delivery</div>
            TOTAL
          </span>
          <span style='float:right; text-align:right;'>
            <div class='thin dense'>$68.75</div>
            <div class='thin dense'>$4.95</div>
            ₹ {{product.price}}
          </span>
        </div>
  </div>
    </div>
        <div class='credit-info'>
          <div class='credit-info-content'>
            
            <img src='https://dl.dropboxusercontent.com/s/ubamyu6mzov5c80/visa_logo%20%281%29.png' height='80' class='credit-card-image' id='credit-card-image'></img>
            Announcement date:  Announced soon

            <span  style="color: red; margin-top: 20px;">*</span> By clicking on proceed you will be atomatically align with our <a href="#">term and condition</a>
            
            <button  href="?action=create_payment" class='pay-btn'><a style="color: white;  text-decoration: none;" href="?action=create_payment">Proceed<a/></button>
          </div>

        

        </div>
      </div>
    </div>




<!-- Payment processeor -->
{% if order is not None %}
<!-- Razorpay Integrations -->
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>

<script>
var options = {
    "key": "rzp_test_tRzIzsfuB2WrqP", // Enter the Key ID generated from the Dashboard
    "name": "Google Giveaway",
    "description": "Payment for {{product.title}}",
    "image": "#",
    "order_id": "{{order.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 2
    "callback_url": "{% url 'order:verify_payment' %}",
    "prefill": {
        "name": "{{user.user_name}}",
        "email": "{{user.email}}",
        "contact": "9999999999"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.open();
</script>
{% endif %}

{% if error %}
<script>
   window.onload = () =>{
     alert("{{error}}")
   }
</script>
{% endif %}
  
</body>
</html>

templates/order/my_order.html
Congratulations you have succefully entered in the course

templates/order/order_fail.html
<div>
<h1 style="font-size:30px;">
fuck.............................
</h1>
</div>